pragma foreign_keys=off;
delete from store_category;
delete from sqlite_sequence where name='store_category';
pragma foreign_keys=on;


-- Categories
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Computers', 'images/computers_1BZTGxx.png', null);
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Laptop', 'images/laptop_F0lqY7m.webp', '1');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Desktop', 'images/delldesktop1_2sccRNQ.webp', '1');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Tablet', 'images/ipad1_vf0qeXv.webp', '1');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Mobile', 'images/mobilephone_HstyrQ0.png', null);
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Apple', 'images/iPhone-logo.jpg', '5');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Samsung', 'images/Samsung-Logo.webp', '5');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Sony', 'images/sonylogo.png', '5');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Motorola', 'images/Motorola-logo.jpg', '5');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Xiaomi', 'images/Mi-logo.jpg', '5');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Accessories', 'images/Accessories_7kWgqWQ.jpg', null);
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Printer', 'images/HP_Deskjet_img4_L9whhEi.webp', '11');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Router & Network', 'images/Asus_4G-AX56U_AX1800_4G_router_with_Wifi_6_img1_audCBZc.webp', '11');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Wireless Keyboard', 'images/DELTACO_wireless_keyboard_img1_6phjFEJ.jpg', '11');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Powerbank', 'images/MagSafe_Charger_Belkin_Boost_Charge_Powerbank_2.5K_img1_u6b5Vd6.webp', '11');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Sound', 'images/Headphones_vuU6941.jpg', null);
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Headphone', 'images/Voxicon_Headphones_GR8_Premium_V.2_ANC_img1_TnIEUVK.webp', '16');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Speaker', 'images/Sudio_Fifty_Wireless_Portable_Speaker_Black_img1_LIALMC1.webp', '16');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Gaming', 'images/gaming2_hVO44Zh.png', null);
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('VR Gaming', 'images/Pico_4_All-in-One_VR_headset_128GB_img1_BXv7jKw_a9NaKCL.webp', '19');
INSERT INTO "store_category" ("name", "image", "ref_id") VALUES ('Gaming Accessories', 'images/gaming2_APLa7gx.png', '19');


-- Inventory
insert into store_inventory ("quantity") values (123);
insert into store_inventory ("quantity") values (34);
insert into store_inventory ("quantity") values (37);
insert into store_inventory ("quantity") values (434);
insert into store_inventory ("quantity") values (53);
insert into store_inventory ("quantity") values (45);
insert into store_inventory ("quantity") values (3);
insert into store_inventory ("quantity") values (45);
insert into store_inventory ("quantity") values (1);
insert into store_inventory ("quantity") values (56);
insert into store_inventory ("quantity") values (23);
insert into store_inventory ("quantity") values (2);
insert into store_inventory ("quantity") values (7);
insert into store_inventory ("quantity") values (9);
insert into store_inventory ("quantity") values (17);
insert into store_inventory ("quantity") values (34);
insert into store_inventory ("quantity") values (12);

insert into store_inventory ("quantity") values (123);
insert into store_inventory ("quantity") values (34);
insert into store_inventory ("quantity") values (37);
insert into store_inventory ("quantity") values (434);
insert into store_inventory ("quantity") values (53);
insert into store_inventory ("quantity") values (45);
insert into store_inventory ("quantity") values (3);
insert into store_inventory ("quantity") values (45);
insert into store_inventory ("quantity") values (1);
insert into store_inventory ("quantity") values (56);
insert into store_inventory ("quantity") values (23);
insert into store_inventory ("quantity") values (2);
insert into store_inventory ("quantity") values (7);
insert into store_inventory ("quantity") values (9);
insert into store_inventory ("quantity") values (17);
insert into store_inventory ("quantity") values (34);
insert into store_inventory ("quantity") values (12);
insert into store_inventory ("quantity") values (123);
insert into store_inventory ("quantity") values (34);
insert into store_inventory ("quantity") values (37);
insert into store_inventory ("quantity") values (434);
insert into store_inventory ("quantity") values (53);
insert into store_inventory ("quantity") values (45);
insert into store_inventory ("quantity") values (3);
insert into store_inventory ("quantity") values (45);
insert into store_inventory ("quantity") values (1);
insert into store_inventory ("quantity") values (56);
insert into store_inventory ("quantity") values (23);
insert into store_inventory ("quantity") values (2);
insert into store_inventory ("quantity") values (7);
insert into store_inventory ("quantity") values (9);
insert into store_inventory ("quantity") values (17);
insert into store_inventory ("quantity") values (34);
insert into store_inventory ("quantity") values (12);
insert into store_inventory ("quantity") values (123);
insert into store_inventory ("quantity") values (34);
insert into store_inventory ("quantity") values (37);
insert into store_inventory ("quantity") values (434);
insert into store_inventory ("quantity") values (53);
insert into store_inventory ("quantity") values (45);
insert into store_inventory ("quantity") values (3);
insert into store_inventory ("quantity") values (45);
insert into store_inventory ("quantity") values (1);
insert into store_inventory ("quantity") values (56);
insert into store_inventory ("quantity") values (23);
insert into store_inventory ("quantity") values (2);
insert into store_inventory ("quantity") values (7);
insert into store_inventory ("quantity") values (9);

-- Products
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Dell Latitude 7480 with Touch i7 16GB 512SSD', '10000', 'Used Dell Latitude 7480 with 1 year warranty! Laptop from Dell with 14" FullHD touch screen, powerful Intel i7 processor, practical backlit keyboard, lightning-fast 512GB SSD hard disk and 16GB RAM. Comes with Windows 10 Pro', 'dell1.png', 'dell2.png', 'dell3.png', 'dell4.png', '2', '1');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('HP EliteBook 830 G5 i5 8GB 256SSD Sure View 120Hz', '14000', 'Used with 1 year warranty! Exclusive HP EliteBook 830 G5 computer in portable format equipped with 13.3-inch Full HD screen 120 Hz full HD, HP Sure View Reflect, powerful Intel Core i5 processor with 4 cores, 8GB RAM and a backlit keyboard!', 'hpelite1.png', 'hpelite2.png', 'hpelite3.png', 'hpelite4.png', '2', '2');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Lenovo Thinkpad L380 i3 8GB 128SSD Windows 10/11', '13000', 'Used with 12 month warranty! High-quality business computer in a compact 13-inch design with good performance through an Intel i3 processor, a fast SSD hard drive of 128 GB and 8 GB of RAM memory. Comes with Windows 10 and free upgrade to Windows 11 is available', 'lenovo.jpg', 'lenovo2.png', 'lenovo3.png', 'lenovo4.png', '2', '3');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('HP ProBook x360 440 G1 i7 16GB 512GB SSD with Touch', '16000', 'Used with 1 year warranty! The HP ProBook x360 440 G1 is a 14-inch portable laptop in HP''s high-quality Probook series, equipped with a reversible Full HD resolution touch screen and with very good performance in the form of a quad-core Intel i7 processor and a fast SSD of 512 GB. The computer comes with Windows 11 Pro.', 'hp_probook.jpg', 'hp2.png', 'hp3.png', 'hp4.png', '2', '4');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('MacBook Pro 15-inch 2019 i9 16GB 512GB SSD Space Gray', '26000', 'Used with 1 year warranty! This is an incredibly powerful model of the 2019  MacBook Pro that comes in a very exclusive, thin and light design for a 15-inch laptop. The laptop is equipped with a bright and high-resolution True Tone Retina display for a great picture and has a super powerful eight-core Intel i9 processor, a lightning-fast SSD and 16 GB of RAM memory!', 'apple.jpg', 'macbook2.jpg', 'macbook3.jpg', 'macbook4.jpg', '2', '5');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('MacBook Pro 2015 Retina A1502 i5 16GB 256SSD (Beg with branded screen)', '17000', 'Used with burnin* on the screen and cover damage with 1 year warranty! Powerful MacBook Pro 2015 model A1502 with amazing 13-inch retina display! This stylish laptop comes with an Intel Core i5 processor and lightning-fast 256GB SSD hard drive.', 'macbook-pro-2015_MrI0f2I.jpg', 'retina2.jpg', 'retina3.jpg', 'retina4.jpg', '2', '6');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Lenovo Tab M10 HD (2nd Gen) ZA6V 4G 32GBAndroid Tablet - Lenovo Tab M10 HD (', '2399', 'The Lenovo Tab M10 is a powerful octa-core Android tablet with a large 10-inch IPS screen, 2GB of RAM and 32GB of storage space! A family tablet for entertainment and with a built-in 4G modem for smooth use with mobile broadband.', 'images/lenovotab1.png', 'images/lenovotab2.png', 'images/lenovotab3.png', 'images/lenovotab4.png', '4', '7');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('iPad (2018) 6th gen 32GB Space Gray', '2199', 'Used with 1 year warranty! iPad 6th generation from 2018 with fantastic retina screen, Touch ID and support for latest iPadOS 16 2022/2023. This is the 32 GB WiFi version in Space Gray!', 'images/ipad1.webp', 'images/ipad2.webp', 'images/ipad3.webp', 'placeholder.png', '4', '8');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Lenovo ThinkPad X1 Tablet 3rd Gen 2-in-1 i5 8GB 256SSD (new* broken box', '7190', 'Lenovo ThinkPad X1 Tablet Gen 3 in original box, mint condition! A strong, large but at the same time very portable tablet that also functions as a laptop with the included keyboard. Comes with a powerful 8th generation Intel i5 processor and a 256GB SSD.', 'images/lenovothinkpad1.webp', 'images/lenovothinkpad2.webp', 'images/lenovothinkpad3.webp', 'placeholder.png', '4', '9');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('HP Chromebook 11 G5 with Touch', '3000', 'Used with 1 year warranty! Very affordable 11.6-inch HP Chromebook G5 with touchscreen and Google''s super-fast and stable ChromeOS. This model has a dual-core Intel processor and a full 4 GB of RAM, which is more than enough for a Chromebook computer. A classic for school or as an everyday surf computer!', 'images/hpbook1.webp', 'images/hpbook2.webp', 'images/hpbook3.webp', 'images/hpbook4.webp', '4', '10');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('HP All-in-One 22-df0000na Intel Processor 4GB 128GB SSD W10S/W11', '4990', 'Stylish and space-saving all-in-one computer built in 22-inch Full HD screen, with dual-core Intel processor and fast SSD for everyday performance. Free upgrade to Windows 11 is available!', 'images/hpdesktop1.webp', 'placeholder.png', 'placeholder.png', 'placeholder.png', '3', '11');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Dell Optiplex 7450 All-in-One i5 16GB 512SSD with DVD', '4599', 'Used with branded screen* and 12 month warranty! Stylish and space-saving all-in-one computer built into a 23-inch Full HD screen and equipped with a strong quad-core Intel i5 processor and fast SSD of 512 GB for best performance.', 'images/delldesktop1.webp', 'images/delldesktop2.webp', 'images/delldesktop3.webp', 'images/delldesktop4.webp', '3', '12');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('iMac 2017 21.5" i5 16GB 1 TB Fusion 4K Retina', '9499', 'Used with Mura brand* screen and 12 month warranty! The super-thin and stylish 21.5-inch iMac with 4K Retina IPS screen and performance that still holds up for everyday life thanks to the quad-core Intel i5 processor and 16GB of RAM. 1-2 days delivery time. Keyboard and mouse not included.', 'images/imac1.webp', 'images/imac2.webp', 'images/imac3.webp', 'images/imac4.webp', '3', '13');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Lenovo ThinkCentre M93z All-in-One i5 16GB 500SSD with Touch', '5399', 'Used with 12 month warranty! Save space on your desk and get great performance with this all-in-one computer built into a 23-inch touch screen with IPS panel and strong quad-core Intel i5 processor. The computer has a whopping 16 GB of RAM memory and a 500 GB SSD hard drive that further improves performance.', 'images/lenovodesk1.webp', 'images/lenovodesk2.webp', 'images/lenovodesk3.webp', 'placeholder.png', '3', '14');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('HP All-in-One 27-dp0004nw 27" Ryzen 5 8GB 512GB SSD Win10/11', '7390', 'Stylish and smartly designed desktop computer from HP with strong six-core AMD Ryzen 5 processor and a spacious and fast SSD of 512 GB built into a Full HD resolution 27-inch IPS screen. Save space but still get excellent performance with HP All-in-One PCs! * Free upgrade to Windows 11!', 'images/hp-all1.webp', 'images/hp-all2.webp', 'images/hp-all3.webp', 'images/hp-all4.webp', '3', '15');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Apple iPhone 14 (128GB, Blue)', '11990', 'iPhone 14 smartphone is equipped with an amazing dual 12 Mpx camera setup with Photonic Engine, powerful A15 Bionic processor and 5G data connection. The large battery lasts longer and has both wired and MagSafe wireless charging.', 'images/iphone1.webp', 'images/iphone2.webp', 'images/iphone3.webp', 'placeholder.png', '6', '16');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('iPhone 13 – 5G smartphone 128GB Pink', '9690', 'New iPhone 13 smartphone has an improved dual 12Mpx camera with sensor-shift OIS and A15 Bionic processor with 5G support and powerful AI functions. It is IP68 certified and very durable.', 'images/iphone-131.webp', 'images/iphone-132.webp', 'images/iphone-133.webp', 'images/iphone-134.webp', '6', '17');

-- New Entries for ProductTable
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Samsung Galaxy S22 128 GB', '12564', 'Samsung Galaxy S22 is a great mobile. Slim design, sharp cameras and a battery that supports wireless battery sharing. The mobile is waterproof according to IP68.', 'images/Samsung_Galaxy_S22_128_GB.jfif', 'images/Samsung_Galaxy_S22_128_GBimg2.jfif', 'images/Samsung_Galaxy_S22_128_GBimg3.jfif', 'placeholder.png', '7', '18');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Samsung Galaxy A04s 32GB', '1890', 'Samsung Galaxy A04s is a nice mobile for those who like experiences. On the big screen, everything you see is crisp, bright, and you scroll without lag. The powerful battery can be fast-charged so you can quickly drive on. And the camera should not be bad just because it is a cheap mobile. So it has 50MP, depth camera and a selfie camera that will make you the star.', 'images/Samsung_Galaxy_A04s_32GBimg1.jfif', 'images/Samsung_Galaxy_A04s_32GBimg2.jfif', 'placeholder.png', 'placeholder.png', '7', '19');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Samsung Galaxy S22 Ultra', '19656', 'Creative, powerful and productive. With the new Galaxy S22 Ultra, you get to experience a world you''ve never seen before. 108 MP camera, waterproof according to IP68 and built-in S Pen.', 'images/Samsung_Galaxy_S22_Ultra_img1.jfif', 'images/Samsung_Galaxy_S22_Ultra_img2.jfif', 'images/Samsung_Galaxy_S22_Ultra_img3.jfif', 'placeholder.png', '7', '20');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Samsung Galaxy S21 FE 128GB', '13644', 'The Samsung Galaxy S21 FE has triple camera with 30x Space Zoom. A powerful battery, fast screen and durable glass. Obviously waterproof according to IP68.', 'images/Samsung_Galaxy_S21_FE_128GB.jfif', 'images/Samsung_Galaxy_S21_FE_128GB_img1.jfif', 'placeholder.png', 'placeholder.png', '7', '21');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Sony Xperia 5 IV 128GB', '12564', 'The Xperia 5 IV has all the power and performance you need to be creative every day. Everything from image processing to watching movies, playing games and sharing your experiences with others can handle it. In a durable and compact design!', 'images/Sony_Xperia_5_IV_128GB.jfif', 'images/Sony_Xperia_5_IV_128GB_img1.jfif', 'images/Sony_Xperia_5_IV_128GB_img2.jfif', 'placeholder.png', '8', '22');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Sony Xperia 10 IV 128GB', '11844', 'The Xperia 10 IV is a durable, durable and durable mobile. It can withstand both water and dust. With the triple camera you capture beautiful images and the powerful 5000 mAh battery lasts a really long time.', 'images/Sony_Xperia_10_IV_128GB_img1.jfif', 'images/Sony_Xperia_10_IV_128GB_img2.jfif', 'placeholder.png', 'placeholder.png', '8', '23');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Sony Xperia PRO-I 512GB', '19764', 'Sony Xperia PRO-I is the mobile that blurs the boundaries between camera and smartphone. With advanced triple camera, large 1.0-type image sensor and smart features such as optical image stabilizer, noise reduction and Sony''s own eye detection (EYE AF), you create nice photos and movies – just like the pros.', 'images/Sony_Xperia_PRO-I_512GB_img1.jfif', 'images/Sony_Xperia_PRO-I_512GB_img2.jfif', 'placeholder.png', 'placeholder.png', '8', '23');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Sony Xperia 5 III 128GB', '14364', 'The Sony Xperia 5 III has a large and powerful 4500mAh battery. It combines powerful performance with compact design. Triple camera with eye autofocus for both animals and humans. The sound is of the highest quality.', 'images/Sony_Xperia_5_III_128GB_img1.jfif', 'images/Sony_Xperia_5_III_128GB_img2.jfif', 'placeholder.png', 'placeholder.png', '8', '24');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Xiaomi 12T Pro 256GB', '12564', 'Groundbreaking 200 MP camera, powerful battery and premium design.An unparalleled image sharpness, low-light capabilities, and fast focus. That''s what characterizes the Xiaomi 12T Pro.Xiaomi 12T Pro has the best battery life so far in a flag cap mobile from Xiaomi. With a large 5,000mAh battery and 120W', 'images/Xiaomi_12T_Pro_256GB.jfif', 'images/Xiaomi_12T_Pro_256GB_img1.jfif', 'images/Xiaomi_12T_Pro_256GB_img2.jfif', 'placeholder.png', '10', '25');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Xiaomi Redmi 10C 64GB', '8964', 'Xiaomi Redmi 10C has a really powerful battery of a whopping 5000 mAh. It has NFC that allows contactless payments. The 3.5mm audio jack allows you to plug in your regular headphones, those that have a round connection.', 'images/Xiaomi_Redmi_10C_64GB.jfif', 'images/Xiaomi_Redmi_10C_64GB_img1.jfif', 'placeholder.png', 'placeholder.png', '10', '26');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Xiaomi 12,256 GB', '12564', 'The Xiaomi 12 comes with a completely new design of the cameras on the back. The Xiaomi 12 has a 50 MP Pro-grand camera with a wide angle. The large aperture of f/1.88 has a large amount of light that brings life and sharpness to your photos. With the 4-in-1 Super Pixel, the image gets more rich in detail. The night mode allows you to both film and shoot in really dark environments. The ultra-wide-angle 13 MP camera has a field of view of 123 degrees. It''s great for taking a photo and getting a', 'images/Xiaomi_12256_GB_img1.jfif', 'images/Xiaomi_12256_GB_img2.jfif', 'images/Xiaomi_12256_GB_img3.jfif', 'placeholder.png', '10', '27');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Xiaomi Redmi Note 11 Pro 5G 128 GB', '10764', 'The Redmi Note 11 Pro 5G has a stylish design, powerful battery and 67W fast charging. A triple camera with awesome lenses. The main camera has a whopping 108-megapixels. In addition, the Redmi Note 11 Pro has 5G support!', 'images/Xiaomi_Redmi_Note_11_Pro_5G_128_GB_img1.jfif', 'images/Xiaomi_Redmi_Note_11_Pro_5G_128_GB_img2.jfif', 'images/Xiaomi_Redmi_Note_11_Pro_5G_128_GB_img3.jfif', 'placeholder.png', '10', '28');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('HP DeskJet 2710e All-in-One Wireless Color Printer', '599', 'HP DeskJet 2710E All-in-One – a small and affordable HP+ inkjet printer. The wireless multifunction printer is perfect for the home office and prints, scans and copies. With WiFi and smart apps, the HP DeskJet 2710E delivers fast and wireless printing wherever you are.', 'images/HP_Deskjet_img2_wtDAzvy.webp', 'images/HP_Deskjet_img4.webp', 'images/HP_Deskjet_img3_3ueq6Ab.webp', 'placeholder.png', '12', '29');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Epson EcoTank ET-2815 Printer -20%', '1999', 'Print, scan and copy – the Epson EcoTank ET-8715 is a small, wireless inkjet printer with WiFi-direct for mobile printing. The printer''s innovative ink filling system is perfect for those who want to print a lot at a low cost.', 'images/Epson_EcoTank_ET-2815_Printer_img1_wC8vkLQ.webp', 'images/Epson_EcoTank_ET-2815_Printer_img2_MZ88YLu.webp', 'images/Epson_EcoTank_ET-2815_Printer_img3_hfb2rT3.webp', 'placeholder.png', '12', '30');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Canon Selphy CP1300, Wireless Photo Printer', '799', 'Small, ultra-compact photo printer that can be connected to smartphone or camera for direct printing of lab-quality photos. The Canon Selphy CP 1300 is small and practical to take with you when traveling or to use in the small home office. It is easy to use and provides many creative possibilities with different printing options and formats. The printer has an 8.1 cm large, vari-angle LCD screen for optimal viewing.', 'images/Canon_Selphy_CP1300_Wireless_Photo_Printer.webp', 'images/Canon_Selphy_CP1300_Wireless_Photo_Printer_img2.webp', 'images/Canon_Selphy_CP1300_Wireless_Photo_Printer_img3.webp', 'placeholder.png', '12', '31');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Canon Selphy CP1300 Photo Printer Wireless', '799', 'Canon Selphy CP 1300 – a small, ultra-compact and easy-to-use photo printer. Connects to a smartphone or camera for direct printing of lab-quality photos. Provides many creative possibilities with different printing options and formats. 8.1 cm large, vari-angle LCD screen.', 'images/Canon_Selphy_CP1300_Photo_Printer_Wireless_img1.webp', 'images/Canon_Selphy_CP1300_Photo_Printer_Wireless_img2.webp', 'images/Canon_Selphy_CP1300_Photo_Printer_Wireless_img3.webp', 'placeholder.png', '12', '32');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Asus router WiFi 6, AX1800, RT-AX53U', '799', 'Asus RT-AX53U is a high-performance router with support for the wireless standard of the future (WiFi 6). Up to 1.8Gbps speed, high security with built-in virus system and parental controls.', 'images/Asus_router_WiFi_6_AX1800_RT-AX53U_img1.webp', 'images/Asus_router_WiFi_6_AX1800_RT-AX53U_img2_1KYCKmX.webp', 'images/Asus_router_WiFi_6_AX1800_RT-AX53U_img3.webp', 'placeholder.png', '13', '33');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('D-link DIR-809, AC750 WiFi 5 wireless router', '399', 'D-Link DIR-809 is an affordable and competent WiFi 5 router. With AC standard and Dual Band, you get WiFi in larger parts of your home at a combined speed of up to 750 Mbps.Advanced security features keep your network and data traffic safe.', 'images/D-link_DIR-809_AC750_WiFi_5_wireless_router_img1.webp', 'images/D-link_DIR-809_AC750_WiFi_5_wireless_router_img2.webp', 'placeholder.png', 'placeholder.png', '13', '34');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('D-link R15 AX1500 WiFi 6 router', '599', 'The D-Link R15 Eagle Pro AI is a wireless router with latest-generation WiFi 6 support and smart AI features that keep performance and security optimized.', 'images/D-link_R15_AX1500_WiFi_6_router_img1.webp', 'images/D-link_R15_AX1500_WiFi_6_router_img2.webp', 'placeholder.png', 'placeholder.png', '13', '35');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Asus 4G-AX56U AX1800 4G router with Wifi 6', '1999', 'Asus 4G-AX56U is a wireless WiFi 6 router with built-in 4G modem of the latest standard LTE Cat 6 that doubles the file transfer speed against the previous LTE Cat 5 standard. The 4G router works with all carriers.', 'images/Asus_4G-AX56U_AX1800_4G_router_with_Wifi_6_img1.webp', 'images/Asus_4G-AX56U_AX1800_4G_router_with_Wifi_6_img2.webp', 'images/Asus_4G-AX56U_AX1800_4G_router_with_Wifi_6_img3.webp', 'placeholder.png', '13', '36');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Powerbank 10000mAh USB-C PD 18 W', '299', 'Powerful power bank with USB-C Power Delivery (18W) and a capacity of 10000 mAh. With 2 ports and Power Delivery, you can quickly and easily charge several mobile phones at the same time.', 'images/Powerbank_10000mAh_USB-C_PD_18_W_img1.webp', 'images/Powerbank_10000mAh_USB-C_PD_18_W_img2.webp', 'images/Powerbank_10000mAh_USB-C_PD_18_W_img3.webp', 'placeholder.png', '15', '37');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Powerbank USB-C 26800 mAh', '799', 'Powerful USB-IF certified battery pack with a capacity of 26800 mAh and support for USB-C and Power Delivery. It provides more battery life and faster charging of your mobile phone or tablet. The auxiliary battery lasts for about 10 charges of a smartphone or 2 charges of a tablet.', 'images/Powerbank_USB-C_26800_mAh_img1.webp', 'images/Powerbank_USB-C_26800_mAh_img2.webp', 'placeholder.png', 'placeholder.png', '15', '38');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Powerbank 20000mAh USB-C PD 27 W', '599', 'Powerful power bank with USB-C Power Delivery (27W) and a capacity of 20000 mAh. With two ports and Power Delivery, you can quickly and easily charge several mobile phones at the same time.', 'images/Powerbank_20000mAh_USB-C_PD_27_W_img1.webp', 'images/Powerbank_20000mAh_USB-C_PD_27_W_img2.webp', 'placeholder.png', 'placeholder.png', '15', '39');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('MagSafe Charger Belkin Boost Charge Powerbank 2.5K', '399', 'Extend your phone''s battery life with a slim power bank you can leave all day on. An LED light will show you when it''s time to charge. Dimensions: 9.7 x 6.5 x 1.3 mm.Easily charged with magnet – MagSafe Belkin Boost Charge BPD002btBK is a wireless power bank with MagSafe', 'images/MagSafe_Charger_Belkin_Boost_Charge_Powerbank_2.5K_img1.webp', 'images/MagSafe_Charger_Belkin_Boost_Charge_Powerbank_2.5K_img2.webp', 'images/MagSafe_Charger_Belkin_Boost_Charge_Powerbank_2.5K_img3.webp', 'placeholder.png', '15', '40');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Belkin Soundform Play Wireless Headphones in Ear', '599', 'Belkin Soundform Play True Wireless – wireless headphones with clear soundstage and powerful bass. Comfortable design that seals against noise. Microphone for clear phone calls.', 'images/Belkin_Soundform_Play_Wireless_Headphones_in_Ear_img1.webp', 'images/Belkin_Soundform_Play_Wireless_Headphones_in_Ear_img3_fcdTiu4.webp', 'images/Belkin_Soundform_Play_Wireless_Headphones_in_Ear_img2_UFk563y.webp', '', '17', '41');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Sony WF-C500 Wireless Headphones, True Wireless', '590', 'With Sony WF-C500 in-ear wireless in-ear headphones, you can move completely freely. Make personalized light settings via the Sony Headphones Connect App. Compatible with Android, iOS, PC and Mac. Up to 20 hours of battery life, hands-free calls and voice assistant.', 'images/Sony_WF-C500_Wireless_Headphones_True_Wireless_img1.webp', 'images/Sony_WF-C500_Wireless_Headphones_True_Wireless_img2.webp', 'images/Sony_WF-C500_Wireless_Headphones_True_Wireless_img3.webp', 'placeholder.png', '17', '42');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Voyager 8200 UC', '2249', 'When it’s time to get in the zone, the stylish, boom-less Voyager 8200 UC Bluetooth® headset puts you there fast. Active noise canceling (ANC) means you only hear what you want to.', 'images/Voyager_8200_UC_img1.webp', 'images/Voyager_8200_UC_img2.webp', 'images/Voyager_8200_UC_img3.webp', 'images/Voyager_8200_UC_img4.webp', '17', '43');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Sony WH-XB910N EXTRA BASS™', '1599', 'Sony WH-XB910N Extra BASS Noise Cancellation Headphones Wireless Bluetooth Over The Ear Headset with Mic, Alexa Voice Control, Google Fast Pair, AUX & Swift Pair, 30Hrs Battery Life (2022 Model)-Black', 'images/Sony_WH-XB910N_EXTRA_BASS_img1.webp', 'images/Sony_WH-XB910N_EXTRA_BASS_img2.webp', 'images/Sony_WH-XB910N_EXTRA_BASS_img3.webp', 'placeholder.png', '17', '44');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('JBL Charge 5 Wireless Portable Speaker (Black)', '1290', 'Enjoy legendary JBL sound with the JBL Charge 5 wireless portable speaker. The speaker comes with specially designed speaker for a JBL Original Pro Sound that sets a new standard for high-quality sound you can carry with you.', 'images/JBL_Charge_5_Wireless_Portable_Speaker_Black_img1_MVQIn6X.webp', 'images/JBL_Charge_5_Wireless_Portable_Speaker_Black_img2_YGyNY20.webp', 'images/JBL_Charge_5_Wireless_Portable_Speaker_Black_img3_QJNnF6m.webp', 'placeholder.png', '18', '45');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Sudio Fifty Wireless Portable Speaker (Black)', '839', 'Sudio Fifty Wireless Portable Speaker allows you to carry with you a high-quality sound no matter where then is going. With its IPX6 rating, you don''t have to worry about wetness or water splashes. The speaker comes with built-in microphone for phone calls.', 'images/Sudio_Fifty_Wireless_Portable_Speaker_Black_img1.webp', 'images/Sudio_Fifty_Wireless_Portable_Speaker_Black_img2.webp', 'images/Sudio_Fifty_Wireless_Portable_Speaker_Black_img3.webp', 'placeholder.png', '18', '46');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Sonos Move speaker (black)', '4090', 'Enjoy music everywhere with Sonos Move speakers that deliver rich sound and voice control. The durable design ensures that the music continues regardless of the weather. Now even with Google Assistant.', 'images/Sonos_Move_speaker_black_img1.webp', 'images/Sonos_Move_speaker_black_img2.webp', 'images/Sonos_Move_speaker_black_img3.webp', 'placeholder.png', '18', '47');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Bose Home Speaker 500 (Black)', '4190', 'The Bose Home Speaker 500 combines a compact design with exceptional sound. Control the speaker through the app, control panel on the speaker or using Amazon Alexa voice control. Connect via WiFi or Bluetooth.', 'images/Bose_Home_Speaker_500_Black_img1.webp', 'images/Bose_Home_Speaker_500_Black_img2.webp', 'images/Bose_Home_Speaker_500_Black_img3.webp', 'placeholder.png', '18', '48');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Pico 4 All-in-One VR headset (256GB)', '5390', 'Play with maximum comfort and without the need for extra cables or equipment thanks to the Pico 4 All-in-One VR headset. The headset comes with two bright LCDs that deliver a resolution of 2160 x 2160p per eye.', 'images/Pico_4_All-in-One_VR_headset_256GB_img1.webp', 'images/Pico_4_All-in-One_VR_headset_256GB_img2.webp', 'images/Pico_4_All-in-One_VR_headset_256GB_img3.webp', 'placeholder.png', '20', '49');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Samsung New Gear VR 2', '996', 'The new Gear VR2 is improved over its predecessor and lets you be immersed in mighty Virtual Reality environments. Can be used for 3D games, 360-degree movies, simulators and apps. Works with Galaxy S6, S6 edge, S6 edge+, S7, S7 edge and Note 7.', 'images/Samsung_New_Gear_VR_2_img1.webp', 'images/Samsung_New_Gear_VR_2_img2.webp', 'images/Samsung_New_Gear_VR_2_img3.webp', 'placeholder.png', '20', '50');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Pico 4 All-in-One VR headset (128GB)', '4690', 'Play with maximum comfort and without the need for extra cables or equipment thanks to the Pico 4 All-in-One VR headset. The headset comes with two bright LCDs that deliver a resolution of 2160 x 2160p per eye.', 'images/Pico_4_All-in-One_VR_headset_128GB_img1_BXv7jKw.webp', 'images/Pico_4_All-in-One_VR_headset_128GB_img3_8Ky1B8z.webp', 'images/Pico_4_All-in-One_VR_headset_128GB_img2_6pliWeI.webp', 'placeholder.png', '20', '51');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Oculus Quest 2 128 GB - White', '5084', 'Upgrade your expectations.Explore incredible games and experiences with unparalleled freedom.A super-fast processor and next-gen graphics.', 'images/Oculus_Quest_2_128_GB_-_White_img1.webp', 'images/Oculus_Quest_2_128_GB_-_White_img2.webp', 'images/Oculus_Quest_2_128_GB_-_White_img3.webp', 'placeholder.png', '20', '52');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('PS5 DualSense wireless controller (Midnight Black)', '487', 'Feel like you''re in the game and have a complete controller with completely redesigned and improved PS5 DualSense wireless control. The vibration technology of haptic feedback together with adaptive triggers (R2 / L2) gives you detailed sensory feedback.', 'images/PS5_DualSense_wireless_controller_Midnight_Black_img1.webp', 'images/PS5_DualSense_wireless_controller_Midnight_Black_img2.webp', 'images/PS5_DualSense_wireless_controller_Midnight_Black_img3.webp', 'placeholder.png', '21', '53');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Hori Nintendo Switch Mario Kart Pro Mini steering wheel racing', '888', 'With the Hori Nintendo Switch Mario Kart Pro Mini racing funnel, you become the king of Nintendo''s racing game.', 'images/Hori_Nintendo_Switch_Mario_Kart_Pro_Mini_steering_wheel_racing_img1.webp', 'images/Hori_Nintendo_Switch_Mario_Kart_Pro_Mini_steering_wheel_racing_img2.jpg', 'images/Hori_Nintendo_Switch_Mario_Kart_Pro_Mini_steering_wheel_racing_img3.jpg', 'placeholder.png', '21', '54');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Corsair Gaming Lapboard for K63 Wireless', '619', 'K63 Wireless Lapboard.Keyboard and mouse pad with wrist rest.Memory foam cushion, Replaceable mouse pad.', 'images/Corsair_Gaming_Lapboard_for_K63_Wireless_img1.webp', 'images/Corsair_Gaming_Lapboard_for_K63_Wireless_img2.webp', 'images/Corsair_Gaming_Lapboard_for_K63_Wireless_img3.webp', 'placeholder.png', '21', '55');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('PowerA Moga Mobile Holder for Gaming (for Xbox controllers)', '279', 'With the PowerA Moga mobile holder for gaming, you can play on your smartphone with your Xbox wireless controller anywhere, anytime. Just attach the holder to the controller, adjust the angle of the phone and start playing.', 'images/PowerA_Moga_Mobile_Holder_for_Gaming_for_Xbox_controllers_img1.webp', 'images/PowerA_Moga_Mobile_Holder_for_Gaming_for_Xbox_controllers_img2.webp', 'images/PowerA_Moga_Mobile_Holder_for_Gaming_for_Xbox_controllers_img3.webp', 'placeholder.png', '21', '56');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Motorola Edge 30 128 GB', '12564', 'The Motorola Edge 30 has a slim and modern design. A powerful battery, triple camera and a super-fast 144 Hz display. It even has 5G!', 'images/Motorola_Edge_30_128_GB_img2.jfif', 'images/Motorola_Edge_30_128_GB_img1.jfif', 'images/Motorola_Edge_30_128_GB_img3.jfif', 'placeholder.png', '9', '57');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Motorola Edge 20 128 GB', '10764', 'The Motorola Edge 20 has a triple camera for all occasions. With 108 megapixels and 30x Super Zoom, the mobile camera is a camera you can trust. Take pictures in ultra-wide angle, macro or telephoto. Videos you can record in 4K.', 'images/Motorola_Edge_20_128_GB_img1.jfif', 'images/Motorola_Edge_20_128_GB_img2.jfif', 'images/Motorola_Edge_20_128_GB_img3.jfif', 'placeholder.png', '9', '58');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Motorola Edge 30 Pro 256 GB', '14364', 'The Motorola Edge 30 Pro has a high-resolution triple camera, crystal clear Dolby Atmos sound and 144 Hz display. The Snapdragon 8 gen 1 processor makes the mobile really fast.', 'images/Motorola_Edge_30_Pro_256_GB_img1.jfif', 'images/Motorola_Edge_30_Pro_256_GB_img2.jfif', 'images/Motorola_Edge_30_Pro_256_GB_img3.jfif', 'placeholder.png', '9', '59');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Motorola Moto E32s smartphone 4/64 (slate gray)', '1990', 'The Motorola Moto E32''s smartphone has a 6.5" 90 Hz display that is perfect for watching content on the go. Take photos and videos with the 16+2+2Mpx camera powered by advanced AI. The 5,000mAh battery allows you to stay connected all day undisturbed.', 'images/Motorola_Moto_E32s_smartphone_img1.webp', 'images/Motorola_Moto_E32s_smartphone_img2.jpg', 'images/Motorola_Moto_E32s_smartphone_img3.webp', 'placeholder.png', '9', '60');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('DELTACO wireless keyboard,105 keys, USB receiver, 10m range, UK layout', '308', 'Wireless slim keyboard with numpad that easily connects to your computer using the compact little USB nano receiver. Perfect keyboard in a stylish office environment.', 'images/DELTACO_wireless_keyboard_img1.jpg', 'images/Corsair_Gaming_Lapboard_for_K63_Wireless_img3_12asKBo.webp', 'images/DELTACO_wireless_keyboard_img3.webp', 'placeholder.png', '14', '61');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('MX Keys Business Wireless Keyboard, Graphite (Nordic)', '3069', 'BUILDERS OF THE FUTUREThe MX Series is designed for people with highly specialized workflow needs like coders, creatives and analysts. With MX Keys for Business, users can type on a keyboard crafted for stability and precision where every keystrok.', 'images/MX_Keys_Business_Wireless_Keyboardimg1.webp', 'images/MX_Keys_Business_Wireless_Keyboardimg2.webp', 'placeholder.png', 'placeholder.png', '14', '62');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Nado Wireless Keyboard Bluetooth Nordic', '329', 'Nado Wireless Bluetooth Keyboard NDNothic keyboard layoutUltra-thin wireless Bluetooth keyboard for your desktop or laptop, tablet &smartphone- Ultra-thin with low weight- Keys with excellent response', 'images/Nado_Wireless_Keyboard_Bluetooth_Nordicimg1.webp', 'images/Nado_Wireless_Keyboard_Bluetooth_Nordicimg2.webp', 'placeholder.png', 'placeholder.png', '14', '63');
INSERT INTO "store_product" ("name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('Logitech MK710 Wireless Combo', '699', 'The normal-sized keyboard features a numeric keypad for better efficiency and a padded wrist rest for maximum convenience. Concave keys place your fingers firmly and their softly rounded edges cause fingertips to slide silently from key to key, hour after hour.', 'images/Logitech_MK710_Wireless_Combo_img1.webp', 'images/Logitech_MK710_Wireless_Combo_img2.webp', 'images/Logitech_MK710_Wireless_Combo_img3.webp', 'placeholder.png', '14', '64');


-- Migration Bug:  Deleting _store_product_old

pragma foreign_keys=off;

alter table store_product rename to _store_product_old;
CREATE TABLE "store_product" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "price" integer NOT NULL, "description" varchar(500) NULL, "image1_url" varchar(100) NOT NULL, "image2_url" varchar(100) NOT NULL, "image3_url" varchar(100) NOT NULL, "image4_url" varchar(100) NOT NULL, "category_id" integer NOT NULL REFERENCES "store_category" ("id"), "inventory_id" integer NOT NULL REFERENCES "store_inventory" ("id"));
insert into store_product select * from _store_product_old;

drop table _store_product_old;

pragma foreign_keys=on;


pragma foreign_keys=off;

alter table store_orderdetail rename to _store_orderdetail_old;
create table "store_orderdetail" ("id" integer not null primary key autoincrement, quantity integer not null, product_id integer not null references "store_product"(id), order_id integer not null references "store_order"(id));

insert into store_orderdetail select * from _store_orderdetail_old;

drop table _store_orderdetail_old;

pragma foreign_keys=on;

