-- Products

INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('1', 'Dell Latitude 7480 with Touch i7 16GB 512SSD', '10000', 'Used Dell Latitude 7480 with 1 year warranty! Laptop from Dell with 14" FullHD touch screen, powerful Intel i7 processor, practical backlit keyboard, lightning-fast 512GB SSD hard disk and 16GB RAM. Comes with Windows 10 Pro', 'dell1.png', 'dell2.png', 'dell3.png', 'dell4.png', '2', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('2', 'HP EliteBook 830 G5 i5 8GB 256SSD Sure View 120Hz', '14000', 'Used with 1 year warranty! Exclusive HP EliteBook 830 G5 computer in portable format equipped with 13.3-inch Full HD screen 120 Hz full HD, HP Sure View Reflect, powerful Intel Core i5 processor with 4 cores, 8GB RAM and a backlit keyboard!', 'hpelite1.png', 'hpelite2.png', 'hpelite3.png', 'hpelite4.png', '2', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('3', 'Lenovo Thinkpad L380 i3 8GB 128SSD Windows 10/11', '13000', 'Used with 12 month warranty! High-quality business computer in a compact 13-inch design with good performance through an Intel i3 processor, a fast SSD hard drive of 128 GB and 8 GB of RAM memory. Comes with Windows 10 and free upgrade to Windows 11 is available', 'lenovo.jpg', 'lenovo2.png', 'lenovo3.png', 'lenovo4.png', '2', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('4', 'HP ProBook x360 440 G1 i7 16GB 512GB SSD with Touch', '16000', 'Used with 1 year warranty! The HP ProBook x360 440 G1 is a 14-inch portable laptop in HP''s high-quality Probook series, equipped with a reversible Full HD resolution touch screen and with very good performance in the form of a quad-core Intel i7 processor and a fast SSD of 512 GB. The computer comes with Windows 11 Pro.', 'hp_probook.jpg', 'hp2.png', 'hp3.png', 'hp4.png', '2', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('5', 'MacBook Pro 15-inch 2019 i9 16GB 512GB SSD Space Gray', '26000', 'Used with 1 year warranty! This is an incredibly powerful model of the 2019  MacBook Pro that comes in a very exclusive, thin and light design for a 15-inch laptop. The laptop is equipped with a bright and high-resolution True Tone Retina display for a great picture and has a super powerful eight-core Intel i9 processor, a lightning-fast SSD and 16 GB of RAM memory!', 'apple.jpg', 'macbook2.jpg', 'macbook3.jpg', 'macbook4.jpg', '2', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('6', 'MacBook Pro 2015 Retina A1502 i5 16GB 256SSD (Beg with branded screen)', '17000', 'Used with burnin* on the screen and cover damage with 1 year warranty! Powerful MacBook Pro 2015 model A1502 with amazing 13-inch retina display! This stylish laptop comes with an Intel Core i5 processor and lightning-fast 256GB SSD hard drive.', 'macbook-pro-2015_MrI0f2I.jpg', 'retina2.jpg', 'retina3.jpg', 'retina4.jpg', '2', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('7', 'Lenovo Tab M10 HD (2nd Gen) ZA6V 4G 32GBAndroid Tablet - Lenovo Tab M10 HD (', '2399', 'The Lenovo Tab M10 is a powerful octa-core Android tablet with a large 10-inch IPS screen, 2GB of RAM and 32GB of storage space! A family tablet for entertainment and with a built-in 4G modem for smooth use with mobile broadband.', 'images/lenovotab1.png', 'images/lenovotab2.png', 'images/lenovotab3.png', 'images/lenovotab4.png', '6', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('8', 'iPad (2018) 6th gen 32GB Space Gray', '2199', 'Used with 1 year warranty! iPad 6th generation from 2018 with fantastic retina screen, Touch ID and support for latest iPadOS 16 2022/2023. This is the 32 GB WiFi version in Space Gray!', 'images/ipad1.webp', 'images/ipad2.webp', 'images/ipad3.webp', 'placeholder.png', '6', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('9', 'Lenovo ThinkPad X1 Tablet 3rd Gen 2-in-1 i5 8GB 256SSD (new* broken box', '7190', 'Lenovo ThinkPad X1 Tablet Gen 3 in original box, mint condition! A strong, large but at the same time very portable tablet that also functions as a laptop with the included keyboard. Comes with a powerful 8th generation Intel i5 processor and a 256GB SSD.', 'images/lenovothinkpad1.webp', 'images/lenovothinkpad2.webp', 'images/lenovothinkpad3.webp', 'placeholder.png', '6', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('10', 'HP Chromebook 11 G5 with Touch', '3000', 'Used with 1 year warranty! Very affordable 11.6-inch HP Chromebook G5 with touchscreen and Google''s super-fast and stable ChromeOS. This model has a dual-core Intel processor and a full 4 GB of RAM, which is more than enough for a Chromebook computer. A classic for school or as an everyday surf computer!', 'images/hpbook1.webp', 'images/hpbook2.webp', 'images/hpbook3.webp', 'images/hpbook4.webp', '6', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('11', 'HP All-in-One 22-df0000na Intel Processor 4GB 128GB SSD W10S/W11', '4990', 'Stylish and space-saving all-in-one computer built in 22-inch Full HD screen, with dual-core Intel processor and fast SSD for everyday performance. Free upgrade to Windows 11 is available!', 'images/hpdesktop1.webp', 'placeholder.png', 'placeholder.png', 'placeholder.png', '3', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('12', 'Dell Optiplex 7450 All-in-One i5 16GB 512SSD with DVD', '4599', 'Used with branded screen* and 12 month warranty! Stylish and space-saving all-in-one computer built into a 23-inch Full HD screen and equipped with a strong quad-core Intel i5 processor and fast SSD of 512 GB for best performance.', 'images/delldesktop1.webp', 'images/delldesktop2.webp', 'images/delldesktop3.webp', 'images/delldesktop4.webp', '3', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('13', 'iMac 2017 21.5" i5 16GB 1 TB Fusion 4K Retina', '9499', 'Used with Mura brand* screen and 12 month warranty! The super-thin and stylish 21.5-inch iMac with 4K Retina IPS screen and performance that still holds up for everyday life thanks to the quad-core Intel i5 processor and 16GB of RAM. 1-2 days delivery time. Keyboard and mouse not included.', 'images/imac1.webp', 'images/imac2.webp', 'images/imac3.webp', 'images/imac4.webp', '3', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('14', 'Lenovo ThinkCentre M93z All-in-One i5 16GB 500SSD with Touch', '5399', 'Used with 12 month warranty! Save space on your desk and get great performance with this all-in-one computer built into a 23-inch touch screen with IPS panel and strong quad-core Intel i5 processor. The computer has a whopping 16 GB of RAM memory and a 500 GB SSD hard drive that further improves performance.', 'images/lenovodesk1.webp', 'images/lenovodesk2.webp', 'images/lenovodesk3.webp', 'placeholder.png', '3', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('15', 'HP All-in-One 27-dp0004nw 27" Ryzen 5 8GB 512GB SSD Win10/11', '7390', 'Stylish and smartly designed desktop computer from HP with strong six-core AMD Ryzen 5 processor and a spacious and fast SSD of 512 GB built into a Full HD resolution 27-inch IPS screen. Save space but still get excellent performance with HP All-in-One PCs! * Free upgrade to Windows 11!', 'images/hp-all1.webp', 'images/hp-all2.webp', 'images/hp-all3.webp', 'images/hp-all4.webp', '3', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('16', 'Apple iPhone 14 (128GB, Blue)', '11990', 'iPhone 14 smartphone is equipped with an amazing dual 12 Mpx camera setup with Photonic Engine, powerful A15 Bionic processor and 5G data connection. The large battery lasts longer and has both wired and MagSafe wireless charging.', 'images/iphone1.webp', 'images/iphone2.webp', 'images/iphone3.webp', 'placeholder.png', '8', '1');
INSERT INTO "main"."store_product" ("id", "name", "price", "description", "image1_url", "image2_url", "image3_url", "image4_url", "category_id", "inventory_id") VALUES ('17', 'iPhone 13 – 5G smartphone 128GB Pink', '9690', 'New iPhone 13 smartphone has an improved dual 12Mpx camera with sensor-shift OIS and A15 Bionic processor with 5G support and powerful AI functions. It is IP68 certified and very durable.', 'images/iphone-131.webp', 'images/iphone-132.webp', 'images/iphone-133.webp', 'images/iphone-134.webp', '8', '1');

-- Categories

INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('1', 'Computers', '');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('2', 'Laptop', '1');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('3', 'Desktop', '1');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('6', 'Tablet', '1');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('7', 'Mobile', '');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('8', 'Apple', '7');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('9', 'Samsung', '7');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('10', 'Sony', '7');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('11', 'Oneplus', '7');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('12', 'Xiaomi', '7');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('13', 'Accessories', '');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('14', 'Printer', '13');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('15', 'Router & Network', '13');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('16', 'Wireless Keyboard', '13');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('17', 'Powerbank', '13');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('18', 'Sound', '');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('19', 'Headphone', '18');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('20', 'Speaker', '18');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('21', 'Gaming', '');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('22', 'VR Gaming', '21');
INSERT INTO "main"."store_category" ("id", "name", "ref_id") VALUES ('23', 'Gaming Accessories', '21');